//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrowserLog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Static {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Static() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrowserLog.Static", typeof(Static).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function() {
        ///    if (typeof (EventSource) !== &quot;undefined&quot;) {
        ///        var scripts = document.getElementsByTagName(&apos;script&apos;);
        ///        var index = scripts.length - 1;
        ///        var myScript = scripts[index];
        ///        var scriptUrl = myScript.src;
        ///        var streamUrl = scriptUrl.substring(0, scriptUrl.length - 13) + &quot;stream&quot;; // 13 being the length of string &quot;BrowserLog.js&quot;
        ///        var source = new EventSource(streamUrl);
        ///        source.onmessage = function(event) {
        ///           console.log(event.data);        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrowserLog {
            get {
                return ResourceManager.GetString("BrowserLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;BrowserLog on {0}&lt;/h1&gt;
        ///    &lt;p&gt;
        ///        Open the console of your browser to see the logs from this server.&lt;br&gt;
        ///        You can use this &lt;a href=&quot;javascript: (function () { var jsCode = document.createElement(&apos;script&apos;); jsCode.setAttribute(&apos;src&apos;, &apos;http://{0}:8081/BrowserLog.js&apos;); document.body.appendChild(jsCode); }());&quot;&gt;Bookmarklet&lt;/a&gt; to open a stre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string homepage {
            get {
                return ResourceManager.GetString("homepage", resourceCulture);
            }
        }
    }
}
